apiVersion: v1
kind: Secret
metadata:
  name: tf-aws-creds
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsCredentials.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsCredentials.secretAccessKey | b64enc }}