{{- if $.Values.alert.enabled -}}
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: argocd-cert-alert
  namespace: {{ $.Values.argocdNamespace| default .Release.Namespace }}
spec:
  schedule: {{ $.Values.alert.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{- if  $.Values.podSecurityContext }}
          securityContext: 
{{ toYaml $.Values.podSecurityContext | indent 12 }}      
          {{- end }}
          serviceAccountName: argocd-cert-sa
          serviceAccount: argocd-cert-sa
          containers:
          - name: argocd-alert-container
            image:  {{ $.Values.alert.image }}
            imagePullPolicy: IfNotPresent
            env:
              - name: devtronNamespace
                value: {{ $.Values.devtronNamespace| default .Release.Namespace }}
              - name: argocdNamespace
                value: {{ $.Values.argocdNamespace| default .Release.Namespace }}
              - name: discordUrl
                value: {{ $.Values.alert.discordUrl | quote }}
              - name: alertBefore
                value: {{ $.Values.alert.alertBefore | quote }}
              - name: cronJobRunAfter
                value: {{ $.Values.alert.cronJobRunAfter | quote }}
            {{- if $.Values.containerSecurityContext }}
            securityContext: 
{{ toYaml $.Values.containerSecurityContext | indent 14 }}         
            {{- end}}
          restartPolicy: OnFailure
{{- end }}