apiVersion: v2
appVersion: 1.0.0
description: A Helm chart for Kubernetes admission policies
maintainers:
- email: devops@devtron.ai
  name: Devtron Devops Team
- email: neha.sharma@devtron.ai
  name: Neha Sharma
name: policychart
type: application
version: 0.1.0
