apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ .Values.name }}
spec:
  serviceAccountName: {{ .Values.serviceAccountName }}
  entrypoint: dag-first
  templates:
    - name: tenant-data-creation
      container:
        image: {{ .Values.tenant_data_creation.image }}:{{ .Values.tenant_data_creation.tag }}
        command: [{{.Values.tenant_data_creation.command}}, "{{.Values.tenant_id}}"]
        envFrom:
          - configMapRef:
              name: f-default
          - secretRef:
              name: f-default
    - name: bake-tenant-dns
      container:
        image: {{ .Values.bake_tenant_dns.image }}:{{ .Values.bake_tenant_dns.tag }}
        command: [{{.Values.bake_tenant_dns.command}}]
        envFrom:
          - configMapRef:
              name: f-default
          - secretRef:
              name: f-default
    - name: entity-data-population
      container:
        image: {{ .Values.entity_data_population.image }}:{{ .Values.entity_data_population.tag }}
        command: [{{.Values.entity_data_population.command_part1}} -t {{ .Values.tenant_id }} -e {{ .Values.entity_data_population.env }} {{.Values.entity_data_population.command_part2}} -t {{ .Values.tenant_id }} -e {{ .Values.entity_data_population.env }}]
        envFrom:
          - configMapRef:
              name: f-default
          - secretRef:
              name: f-default
    - name: dag-first
      dag:
        tasks:
          - name: tenant-data-creation
            template: tenant-data-creation
          - name: bake-tenant-dns
            dependencies: [tenant-data-creation]
            template: bake-tenant-dns
          - name: entity-data-population
            dependencies: [tenant-data-creation]
            template: entity-data-population