{{- if $.Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.secrets.name }}
  namespace: {{ $.Values.scoopNamespace | default .Release.Namespace }}
type: {{ $.Values.secrets.type }}
{{- if $.Values.secrets.data }}
data:
  {{- range $.Values.secrets.data }}
  {{ .key | quote }}: {{ .value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}