{{- if $.Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: scoop-secret
  namespace: {{ $.Values.scoopnamespace | default .Release.Namespace }}
type: Opaque
{{- if $.Values.secrets.data }}
data:
{{ toYaml $.Values.secrets.data | indent 2 }}
{{- end }}
{{- end }}

