{{- if $.Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.secrets.name }}
  namespace: {{ $.Values.scoopNamespace | default .Release.Namespace }}
type: Opaque
{{- if $.Values.secrets.data }}
data:
{{ toYaml $.Values.secrets.data | indent 2 }}
{{- end }}
{{- end }}

---

{{- if $.Values.scoop.imagePullSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: scoop-imagepull-secret
  namespace: {{ $.Values.scoopNamespace | default .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{- if $.Values.scoop.imagePullSecrets.data}}
data:
{{ toYaml $.Values.scoop.imagePullSecrets.data | indent 2 }}
{{- end }}
{{- end }}
