apiVersion: v1
kind: Service
metadata:
  name: scoop-service
  labels:
    app: scoop-chart
  {{- if $.Values.labels }}
{{ toYaml .Values.labels | indent 2 }}
  {{- end }}
  namespace: {{ $.Values.scoopnamespace | default .Release.Namespace }}   
spec:
  {{- with $.Values.service.type }}
  type: {{ $.Values.service.type }}
  {{- end }}
  ports:
      {{- with $.Values.service.port }}
    - port: {{ $.Values.service.port }}
      {{- end }}
      targetPort: 8080
      protocol: TCP
      name: app
  selector:
    app: scoop-chart
    