# deployment-chart-4-18-0-4.18.0urce: deployment-chart-4-18-0/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "release-name-deployment-chart-4-18-0-service"
  labels:
    app: "deployment-chart-4-18-0"
    release: "release-name"
  {{- if $.Values.labels }}
{{ toYaml .Values.labels | indent 2 }}
  {{- end }}
  namespace: {{ $.Values.scoopnamespace | default .Release.Namespace }}
    
spec:
  {{- with $.Values.service.type }}
  type: {{ $.Values.service.type }}
  {{- end }}
  ports:
      {{- with $.Values.service.port }}
    - port: {{ $.Values.service.port }}
      {{- end }}
      targetPort: 80
      protocol: TCP
      name: app
  selector:
    app: "deployment-chart-4-18-0"
    