{{- if $.Values.denyRoleCreationPolicy.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ include "policychart.fullname" . }}-deny-role-creation
spec:
  failurePolicy: Fail
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
    resourceRules:
    - apiGroups:
      - rbac.authorization.k8s.io
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - clusterroles
      - roles
      scope: '*'
  validations:
  - expression: "false"
    message: Creation of ClusterRole and Role is not allowed.
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "policychart.fullname" . }}-deny-role-creation-binding
spec:
  matchResources:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
  policyName: {{ include "policychart.fullname" . }}-deny-role-creation
  validationActions:
    - Deny
{{- end }}
