{{- if $.Values.denyCLusterRoleBindingCreation.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ include "policychart.fullname" . }}restrict-cluster-admin-binding
spec:
  failurePolicy: Fail
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
    resourceRules:
    - apiGroups:
      - rbac.authorization.k8s.io
      apiVersions:
      - "*"
      operations:
      - CREATE
      - UPDATE
      resources:
      - clusterrolebindings
      scope: '*'
  validations:
    - expression: "!(object.roleRef.apiGroup == 'rbac.authorization.k8s.io' && 
                     object.roleRef.kind == 'ClusterRole' && 
                     object.roleRef.name == 'cluster-admin')"
      message: "Binding to the cluster-admin ClusterRole is not allowed due to security policy."
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "policychart.fullname" . }}restrict-cluster-admin-binding-policy
spec:
  policyName: {{ include "policychart.fullname" . }}restrict-cluster-admin-binding
  validationActions:
  {{- range .Values.denyPvcCreationPolicy.validationActions }}
  - {{ . }}
  {{- end }}
{{- end }}

