{{- if .Values.restrictWithoutResourcesPolicy.policies.restrictResourceLimitsPolicy.enabled }}
{{- $maxCPU := .Values.restrictWithoutResourcesPolicy.policies.restrictResourceLimitsPolicy.maxCPULimit | default "1000m" }}
{{- $maxMemory := .Values.restrictWithoutResourcesPolicy.policies.restrictResourceLimitsPolicy.maxMemoryLimit | default "2Gi" }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ include "policychart.fullname" . }}-restrict-resource-limits
spec:
  failurePolicy: Fail
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          {{- range .Values.restrictWithoutResourcesPolicy.policies.restrictResourceLimitsPolicy.namespaces }}
          - {{ . | quote }}
          {{- end }}
    objectSelector: {}
    resourceRules:
      - apiGroups:
          - ""
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - deployments
          - statefulsets
        scope: Namespaced
  validations:
  - expression: |-
      has(object.spec.template) ?
      (
        !has(object.spec.template.spec.containers[0].resources.limits) || (
          (!has(object.spec.template.spec.containers[0].resources.limits.cpu) ||
           quantity(object.spec.template.spec.containers[0].resources.limits.cpu).compareTo(quantity('{{ $maxCPULimit }}')) <= 0) &&
          (!has(object.spec.template.spec.containers[0].resources.limits.memory) ||
           quantity(object.spec.template.spec.containers[0].resources.limits.memory).compareTo(quantity('{{ $maxMemoryLimit }}')) <= 0)
        )
      ) :
      (
        !has(object.spec.containers[0].resources.limits) || (
          (!has(object.spec.containers[0].resources.limits.cpu) ||
           quantity(object.spec.containers[0].resources.limits.cpu).compareTo(quantity('{{ $maxCPULimit }}')) <= 0) &&
          (!has(object.spec.containers[0].resources.limits.memory) ||
           quantity(object.spec.containers[0].resources.limits.memory).compareTo(quantity('{{ $maxMemoryLimit }}')) <= 0)
        )
      )
    message: "Resource limits exceed the maximum allowed. CPU must be <= {{ $maxCPULimit }} and memory must be <= {{ $maxMemoryLimit }}."
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "policychart.fullname" . }}-restrict-resource-limits-binding
spec:
  policyName: {{ include "policychart.fullname" . }}-restrict-resource-limits
  validationActions:
    - Deny
{{- end }}
