{{- if $.Values.loadBalancerCreationPolicy.enabled}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ include "policychart.fullname" . }}-deny-loadbalancer-creation
spec:
  failurePolicy: Fail
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          {{- range .Values.loadBalancerCreationPolicy.namespaces }}
          - {{ . | quote }}
          {{- end }}
    objectSelector: {}
    resourceRules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - services
      scope: Namespaced
  validations:
  - expression: object.spec.type != 'LoadBalancer'
    message: Creation of Services with type LoadBalancer is not allowed.
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "policychart.fullname" . }}-deny-loadbalancer-creation-binding
spec:
  matchResources:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
  policyName: {{ include "policychart.fullname" . }}-deny-loadbalancer-creation
  validationActions:
  {{- range .Values.loadBalancerCreationPolicy.validationActions }}
  - {{ . }}
  {{- end }}
{{- end }}
