{{- if $.Values.withoutReadinessandLivenessProbe.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ include "policychart.fullname" . }}-require-probes-policy
spec:
  failurePolicy: Fail
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          {{- range .Values.withoutReadinessandLivenessProbe.namespaces }}
          - {{ . | quote }}
          {{- end }}
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
        scope: Namespaced
  validations:
    - expression: "object.spec.containers.all(c, has(c.readinessProbe) && has(c.livenessProbe))"
      message: "All containers in the pod must have both a readiness probe and a liveness probe defined."
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "policychart.fullname" . }}-require-probes-policy-binding
spec:
  policyName: {{ include "policychart.fullname" . }}-require-probes-policy
  validationActions:
  {{- range .Values.denyPvcCreationPolicy.validationActions }}
  - {{ . }}
  {{- end }}
{{- end }}
