{{- if $.Values.appDeletionPolicy.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ include "k8s-shield.fullname" . }}-prevent-app-deletion
spec:
  failurePolicy: Fail
  {{- if and .Values.appDeletionPolicy.namespaces }}
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          {{- range .Values.appDeletionPolicy.namespaces }}
          - {{ . | quote }}
          {{- end }}
  {{- else }}
  matchConstraints: {}
  {{- end }}
  objectSelector: {}
  resourceRules:
    - apiGroups:
        - argoproj.io
      apiVersions:
        - v1alpha1
      operations:
        - DELETE
      resources:
        - applications
      scope: Namespaced
  validations:
    - expression: "false"
      message: Deletion of application is not allowed.
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "k8s-shield.fullname" . }}-prevent-app-deletion-binding
spec:
  matchResources:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
  policyName: {{ include "k8s-shield.fullname" . }}-prevent-app-deletion
  validationActions:
  {{- range .Values.appDeletionPolicy.validationActions }}
  - {{ . }}
  {{- end }}
{{- end }}