{{- if and $.Values.defaultPolicies.create $.Values.defaultPolicies.policies.appDeletionPolicy }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ include "k8s-shield.fullname" . }}-prevent-app-deletion
spec:
  failurePolicy: Fail
  matchConstraints:
    matchPolicy: Equivalent
    {{- if .Values.policyDefinitions.appDeletionPolicy.namespaces }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            {{- range .Values.policyDefinitions.appDeletionPolicy.namespaces }}
            - {{ . | quote }}
            {{- end }}
    {{- end }}
    resourceRules:
      - apiGroups:
          - argoproj.io
        apiVersions:
          - v1alpha1
        operations:
          - DELETE
        resources:
          - applications
        scope: Namespaced
  objectSelector: {}
  validations:
    - expression: "false"
      message: Deletion of application is not allowed.
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "k8s-shield.fullname" . }}-prevent-app-deletion
spec:
  policyName: {{ include "k8s-shield.fullname" . }}-prevent-app-deletion
  matchResources:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
  validationActions:
    {{- range .Values.policyDefinitions.appDeletionPolicy.validationActions }}
    - {{ . }}
    {{- end }}
{{- end }}