tenant_id: "testTenant"
serviceAccountName: "cd-runner"
name: "tenant-onboarding"
tenant_data_creation:
  image: 429738059147.dkr.ecr.ap-south-1.amazonaws.com/platform-coreos/tenant-onboarding
  tag: 1.0.72
  command: '"yarn", "run", "script", "to", "-s", "all", "-w", "query", "-t"'
  
bake_tenant_dns:
  image: 429738059147.dkr.ecr.ap-south-1.amazonaws.com/platform-infra/dns-create-delete-docker-image
  tag: 1.0.2
  command: "./upsert-dns-recordset.sh"

entity_data_population:
  image: 429738059147.dkr.ecr.ap-south-1.amazonaws.com/platform-coreos/tenant-onboarding
  tag: 1.0.72
  env: test
  command_part1: "yarn script csvToDb csv -f entity_script/csvs/event.csv -w event -k coreos"
  command_part2: "yarn script csvToDb csv -f entity_script/csvs/reason.csv -w reason -k coreos"