tenant_id: ""
serviceAccountName: "cd-runner"
tenant_data_creation:
  image: 429738059147.dkr.ecr.ap-south-1.amazonaws.com/platform-coreos/tenant-onboarding
  tag: 1.0.72

bake_tenant_dns:
  image: 429738059147.dkr.ecr.ap-south-1.amazonaws.com/platform-infra/dns-create-delete-docker-image
  tag: 1.0.2

entity_data_population:
  image: 429738059147.dkr.ecr.ap-south-1.amazonaws.com/platform-coreos/tenant-onboarding
  tag: 1.0.72
  env: test
