data:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: sample-metrics-app
    name: sample-metrics-app
    namespace: default
  spec:
    ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: sample-metrics-app
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: sample-metrics-app
    name: sample-metrics-app
    namespace: default
  spec:
    ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: sample-metrics-app
    sessionAffinity: None
    type: ClusterIP
