name: "example-gke-cluster"
project_id: "your-gcp-project-id" # TODO: Replace with your GCP project ID
region: "us-central1"
cluster_version: "1.28" # Specify desired GKE version
network: "default"
subnetwork: "default"
machine_type: "e2-medium"
node_count: 1
node_locations:
  - "us-central1-a"
# Example tags, adapt as needed
resource_tags:
  team: "Devops_Team"
  environment: "non-production"
  cost_center: "your-cost-center"

# Terraform controller specific values (can remain common)
path: "./terraform/gke-auto-mode" # This path is an assumption
approvePlan: "auto"
destroyResourcesOnDeletion: false
alwaysCleanupRunnerPod: false
force: false

# Runner pod specific (can remain common or be adapted)
# affinity: {}
# tolerations: []
