{{- if .Values.argocd_backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.argocd_backup.serviceAccountName }}
  name: {{ .Values.argocd_backup.serviceAccountName }}
  namespace: devtroncd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.argocd_backup.serviceAccountName }}
  name: {{ .Values.argocd_backup.serviceAccountName }}
  namespace: devtroncd
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  - applicationsets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.argocd_backup.serviceAccountName }}
  name: {{ .Values.argocd_backup.serviceAccountName }}
  namespace: devtroncd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.argocd_backup.serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.argocd_backup.serviceAccountName }}
{{- end }}