{{- if .Values.rbac.create }}
apiVersion: {{ .Values.rbacapiversion }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "coralogix-fluentd.name" . }}-service-account
  namespace: kube-system
  labels:
    k8s-app: {{ template "coralogix-fluentd.fullname" . }}
    k8s-app-version: {{ .Chart.AppVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "coralogix-fluentd.name" . }}-service-account-role
subjects:
- kind: ServiceAccount
  name: {{ template "coralogix-fluentd.name" . }}-service-account
  namespace: kube-system
{{- end }}
