apiVersion: v1
appVersion: 0.1.0
description: Helm chart to deploy argocd certificate refresh CronJob.
maintainers:
- email: ajay@devtron.ai
  name: Ajay
- email: badal@devtron.ai
  name: Badal Kumar
name: argocd-certificate-refresh
version: 0.10.8
