# Default values for argocd-certificate-refresh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# docker image information
image: quay.io/devtron/argocd-cert-refresh:v10
#accepted values are ENTERPRISE & OSS 
# clusterType: ENTERPRISE
# If not namespace is provided then by default it will take in which namespace it will deploy
# devtronNamespace: devtroncd
# argocdNamespace: devtroncd




# values for cronjob
#currently it will run At 23:59 on 1st day-of-month in every 6th month
cronjob:
  schedule: "59 23 1 */6 *"




#set up this If you need alert for argocd cert expire
alert:
  enabled: false
  image: quay.io/devtron/argocd-cert-refresh:alert-v9
  discordUrl: "" 
  #Daily At 07:00AM GMT so it will be 12:30PM in IST
  schedule: "0 7 * * *"
  # if the certificate will expire after 10 days you will get alert
  alertBefore: 10
  # if the next cron will be run after 2 days you will get alert
  cronJobRunAfter: 2



podSecurityContext: {}
  # runAsGroup: 1000
  # runAsUser: 1000
containerSecurityContext: {}
    # allowPrivilegeEscalation: false
    # runAsUser: 1000
    # runAsNonRoot: true
