apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: renew-ecr-k8s-creds-rolebinding
  namespace:  {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace:  {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: renew-ecr-k8s-creds-role
  apiGroup: rbac.authorization.k8s.io
