name: "example-openshift-cluster" # Name for the Helm release
openshift_version: "4.14" # Specify desired OpenShift version
platform: "vsphere" # Example: vsphere, aws, azure, baremetal. This choice dictates other variables.
base_domain: "example.com" # Base domain for the OpenShift cluster
cluster_name: "myocp"      # Name of the OpenShift cluster itself

# Pull secret is sensitive and large, often fetched from a K8s secret or environment variable in real TF
# For Helm values, it might be provided directly or fetched by TF from a secure source.
# Providing it as a string here, expecting it to be JSON.
pull_secret: "{ \"auths\": { \"cloud.openshift.com\": { \"auth\": \"YOUR_PULL_SECRET_AUTH_BASE64_ENCODED\", \"email\": \"you@example.com\" } } }" # TODO: Replace with actual pull secret JSON
ssh_public_key: "ssh-rsa AAAA..." # TODO: Replace with your SSH public key for node access

# These are very generic; actual TF would need much more detail based on platform
control_plane_replicas: 3
worker_replicas: 3
# master_instance_type: "m5.xlarge" # Example if on AWS
# worker_instance_type: "m5.xlarge" # Example if on AWS

# Example tags (applicability depends on the underlying provider)
resource_tags:
  team: "Devops_Team"
  environment: "non-production"
  project: "openshift-project"

# Terraform controller specific values
path: "./terraform/openshift-auto-mode" # This path is an assumption
approvePlan: "auto"
destroyResourcesOnDeletion: false
alwaysCleanupRunnerPod: false
force: false

# Runner pod specific (can remain common or be adapted)
# affinity: {}
# tolerations: []
