{{- if and $.Values.defaultPolicies.create $.Values.defaultPolicies.policies.pvcCreationPolicy }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ include "k8s-shield.fullname" . }}-restrict-pvc-creation
spec:
  failurePolicy: Fail
  {{- if and .Values.policyDefinitions.pvcCreationPolicy.namespaces }}
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector: 
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          {{- range .Values.policyDefinitions.pvcCreationPolicy.namespaces }}
          - {{ . | quote }}
          {{- end }}
  {{- else }}
  matchConstraints: {}
  {{- end }}
  objectSelector: {}
  resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      scope: Namespaced
      resources: ["persistentvolumeclaims"]
  validations:
  {{- if and .Values.excludeLabel.key .Values.excludeLabel.value }}
    - expression: "has(object.metadata.labels) && object.metadata.labels['{{ .Values.excludeLabel.key }}'] == '{{ .Values.excludeLabel.value }}'"
      message: "Creation of PersistentVolumeClaims is not allowed, set label {{ .Values.excludeLabel.key }}: {{ .Values.excludeLabel.value }} to allow" 
  {{- else }}
    - expression: "false"
      message: "Creation of PersistentVolumeClaims is not allowed."
  {{- end }}
---  
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "k8s-shield.fullname" . }}-restrict-pvc-creation
spec:
  matchResources:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
  policyName: {{ include "k8s-shield.fullname" . }}-restrict-pvc-creation
  validationActions:
  {{- range .Values.policyDefinitions.pvcCreationPolicy.validationActions }}
  - {{ . }}
  {{- end }}
{{- end }}
