{{- if and $.Values.defaultPolicies.create $.Values.defaultPolicies.policies.limitResourcePolicy }}
{{- $maxCPU := .Values.policyDefinitions.resourcePolicies.limitResourcePolicy.maxCPULimit | default "1000m" }}
{{- $maxMemory := .Values.policyDefinitions.resourcePolicies.limitResourcePolicy.maxMemoryLimit | default "2Gi" }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ include "k8s-shield.fullname" . }}-restrict-resource-limits
spec:
  failurePolicy: Fail
  {{- if and .Values.policyDefinitions.resourcePolicies.limitResourcePolicy.namespaces }}
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          {{- range .Values.policyDefinitions.resourcePolicies.limitResourcePolicy.namespaces }}
          - {{ . | quote }}
          {{- end }}
  {{- else }}
  matchConstraints: {}
  {{- end }}
  objectSelector: {}
  resourceRules:
    - apiGroups:
        {{- range $.Values.policyDefinitions.resourcePolicies.limitResourcePolicy.apiGroups }}
        - {{ . | quote }}
        {{- end }}
      apiVersions:
        - v1
      operations:
        {{- range .Values.policyDefinitions.resourcePolicies.limitResourcePolicy.operations }}
        - {{ . | quote }}
        {{- end }}
      resources:
        {{- range .Values.policyDefinitions.resourcePolicies.limitResourcePolicy.resources }}
        - {{ . | quote }}
        {{- end }}
      scope: Namespaced
  validations:
  {{- if and .Values.excludeLabel.key .Values.excludeLabel.value }}
    - expression: |-
        (has(object.metadata.labels) && object.metadata.labels['{{ .Values.excludeLabel.key }}'] == '{{ .Values.excludeLabel.value }}') 
        || (
          has(object.spec.template) ?
          (
            !has(object.spec.template.spec.containers[0].resources.limits) || (
              (!has(object.spec.template.spec.containers[0].resources.limits.cpu) ||
               quantity(object.spec.template.spec.containers[0].resources.limits.cpu).compareTo(quantity('{{ $maxCPU }}')) <= 0) &&
              (!has(object.spec.template.spec.containers[0].resources.limits.memory) ||
               quantity(object.spec.template.spec.containers[0].resources.limits.memory).compareTo(quantity('{{ $maxMemory }}')) <= 0)
            )
          ) :
          (
            !has(object.spec.containers[0].resources.limits) || (
              (!has(object.spec.containers[0].resources.limits.cpu) ||
               quantity(object.spec.containers[0].resources.limits.cpu).compareTo(quantity('{{ $maxCPU }}')) <= 0) &&
              (!has(object.spec.containers[0].resources.limits.memory) ||
               quantity(object.spec.containers[0].resources.limits.memory).compareTo(quantity('{{ $maxMemory }}')) <= 0)
            )
          )
        )
      message: "Resource limits exceed the maximum allowed: CPU <= {{ $maxCPU }} and memory <= {{ $maxMemory }}, set label {{ .Values.excludeLabel.key }}: {{ .Values.excludeLabel.value }} to allow"
  {{- else }}
    - expression: |-
        has(object.spec.template) ?
        (
          !has(object.spec.template.spec.containers[0].resources.limits) || (
            (!has(object.spec.template.spec.containers[0].resources.limits.cpu) ||
             quantity(object.spec.template.spec.containers[0].resources.limits.cpu).compareTo(quantity('{{ $maxCPU }}')) <= 0) &&
            (!has(object.spec.template.spec.containers[0].resources.limits.memory) ||
             quantity(object.spec.template.spec.containers[0].resources.limits.memory).compareTo(quantity('{{ $maxMemory }}')) <= 0)
          )
        ) :
        (
          !has(object.spec.containers[0].resources.limits) || (
            (!has(object.spec.containers[0].resources.limits.cpu) ||
             quantity(object.spec.containers[0].resources.limits.cpu).compareTo(quantity('{{ $maxCPU }}')) <= 0) &&
            (!has(object.spec.containers[0].resources.limits.memory) ||
             quantity(object.spec.containers[0].resources.limits.memory).compareTo(quantity('{{ $maxMemory }}')) <= 0)
          )
        )
      message: "Resource limits exceed the maximum allowed: CPU <= {{ $maxCPU }} and memory <= {{ $maxMemory }}."
  {{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "k8s-shield.fullname" . }}-restrict-resource-limits
spec:
  policyName: {{ include "k8s-shield.fullname" . }}-restrict-resource-limits
  validationActions:
  {{- range .Values.policyDefinitions.resourcePolicies.limitResourcePolicy.validationActions }}
  - {{ . }}
  {{- end }}
{{- end }}