apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ai-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: ai-agent
spec:
  selector:
    app: ai-agent
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5050