{{- if  $.Values.withoutResourcesPolicy.policies.restrictResourceLimitsresourcesPolicy.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ include "policychart.fullname" . }}-restrict-resource-limits
spec:
  failurePolicy: Fail
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          {{- range .Values.withoutResourcesPolicy.policies.restrictResourceLimitsresourcesPolicy.namespaces }}
          - {{ . | quote }}
          {{- end }}
    objectSelector: {}
    resourceRules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - deployments
          - statefulsets
        scope: Namespaced
  validations:
    - expression: |-
        !has(object.spec.template.spec.containers[0].resources.limits) || (
          (!has(object.spec.template.spec.containers[0].resources.limits.cpu) ||
           quantity(object.spec.template.spec.containers[0].resources.limits.cpu).compareTo(quantity('1000m')) <= 0) &&
          (!has(object.spec.template.spec.containers[0].resources.limits.memory) ||
          quantity(object.spec.template.spec.containers[0].resources.limits.memory).compareTo(quantity('2Gi')) <= 0)
        )
      message: "Resource limits exceed the maximum allowed. CPU must be <= 1 and memory must be <= 2Gi."
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "policychart.fullname" . }}-restrict-resource-limits-binding
spec:
  policyName: {{ include "policychart.fullname" . }}-restrict-resource-limits
  validationActions:
    - Deny
{{- end }}
