apiVersion: v2
name: devtron-enterprise
appVersion: 32.1.1
description: Chart to configure and install Devtron Enterprise Stack. Devtron is a Kubernetes Orchestration system.
keywords:
  - Devtron
  - Kubernetes
  - Orchestration
  - K8s
  - Deployment
  - argocd
  - Hyperion
version: 32.1.1
sources:
  - https://github.com/devtron-labs/charts/tree/main/charts/devtron-enterprise
dependencies:
- name: devtron-operator
  version: "0.x.x"
  repository: https://helm.devtron.ai/
  alias: devtron
maintainers:
- email: prakarsh@devtron.ai
  name: Prakarsh
icon: https://s3-ap-southeast-1.amazonaws.com/devtron.ai/images/devtron-sqr-logo.png
home: https://devtron.ai
