global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true
  containerRegistry: "quay.io/devtron"
  # The below values can be specified both at global as well as component level
  # nodeSelector:
  #   key: value
  # tolerations:
  #   - key: "key1"
  #     operator: "Equal"
  #     value: "value1"
  #     effect: "NoSchedule"
  # imagePullSecrets:
  #     - name: your-image-pull-secret
devtron:
  installer:
    repo: "devtron-labs/charts"
    release: "32.1.4"
    registry: ""
    image: inception
    tag: 7beef376-948-31378
    source: "github" # Available options are github and gitee
  components:
    # Values for dashboard
    dashboard:
      config:
        extraConfigs:
          HIDE_DISCORD: "true"
          HIDE_RELEASES: "false"
          HIDE_RESOURCE_WATCHER: "false"
          FEATURE_SCOPED_VARIABLE_ENVIRONMENT_LIST_ENABLE: "true"
          FEATURE_IMAGE_PROMOTION_ENABLE: "true"
          FEATURE_CLUSTER_MAP_ENABLE: "true"
          FEATURE_CONFIG_DRIFT_ENABLE: "true"
      image: "dashboard:837160d0-d0729419-931-31524"
    # Values for devtron
    devtron:
      image: "hyperion:8f168d4e-759-31827"
      cicdImage: "devtron:9291b79f-930-32282"
      imagePullPolicy: IfNotPresent
      customOverrides:
        PG_ADDR: postgresql-postgresql.devtroncd
        USE_CUSTOM_HTTP_TRANSPORT: "false"
        ASYNC_BUILDX_CACHE_EXPORT: "false"
        BUILDX_CACHE_MODE_MIN: "false"
        CLONING_MODE: FULL
        SCOPED_VARIABLE_ENABLED: "true"
        SCOPED_VARIABLE_HANDLE_PRIMITIVES: "true"
        DEVTRON_CHART_ARGO_CD_INSTALL_REQUEST_TIMEOUT: "1"
        IS_INTERNAL_USE: "true"
        IS_AIR_GAP_ENVIRONMENT: "false"
        DEVTRON_MANAGED_LICENSING_ENABLED: "false"
    # Values for ciRunner
    ciRunner:
      image: "ci-runner:2168a861-882-31228"
    # Values for kubelink
    kubelink:
      image: "kubelink:fd7b49f0-314-31414"
      imagePullPolicy: IfNotPresent
    # Values for gitsensor
    gitsensor:
      image: "git-sensor:fd7b49f0-950-31385"
      imagePullPolicy: IfNotPresent
    chartSync:
      image: chart-sync:2168a861-341-31218
  # values for security integration
  security:
    imageScanner:
      image: "image-scanner:fd7b49f0-109-31386"
      configs:
        TRIVY_DB_REPOSITORY: mirror.gcr.io/aquasec/trivy-db
        TRIVY_JAVA_DB_REPOSITORY: mirror.gcr.io/aquasec/trivy-java-db
  devtronEnterprise:
    enabled: true
    casbin:
      image: "casbin:fd7b49f0-fced3ae3-464-31402"
      imagePullPolicy: IfNotPresent
    scoop:
      enabled: false
      image: "scoop:30f26a6c-955-31521"
      imagePullPolicy: IfNotPresent
