global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true
  containerRegistry: "quay.io/devtron"
  # The below values can be specified both at global as well as component level
  # nodeSelector:
  #   key: value
  # tolerations:
  #   - key: "key1"
  #     operator: "Equal"
  #     value: "value1"
  #     effect: "NoSchedule"
  # imagePullSecrets:
  #     - name: your-image-pull-secret
  dbConfig:
    PG_ADDR: postgresql-postgresql.devtroncd
    PG_PORT: "5432"
    PG_USER: postgres
    PG_DATABASE: orchestrator
devtron:
  installer:
    repo: "devtron-labs/charts"
    release: "41.0.0"
    registry: ""
    arch: "multi-arch"
    image: inception
    tag: 7beef376-948-31378
    source: "github" # Available options are github and gitee
  components:
    # Values for dashboard
    dashboard:
      config:
        extraConfigs:
          HIDE_DISCORD: "true"
          HIDE_RELEASES: "false"
          HIDE_RESOURCE_WATCHER: "false"
          FEATURE_SCOPED_VARIABLE_ENVIRONMENT_LIST_ENABLE: "true"
          FEATURE_IMAGE_PROMOTION_ENABLE: "true"
          FEATURE_CLUSTER_MAP_ENABLE: "true"
          FEATURE_CONFIG_DRIFT_ENABLE: "true"
      image: "dashboard:6ae4cee5-f4daa444-931-35579"
    # Values for devtron
    devtron:
      image: "hyperion:75a2edd0-759-35584"
      cicdImage: "devtron:1e821a48-930-36105"
      imagePullPolicy: IfNotPresent
      customOverrides:
        PG_ADDR: postgresql-postgresql.devtroncd
        USE_CUSTOM_HTTP_TRANSPORT: "false"
        ASYNC_BUILDX_CACHE_EXPORT: "false"
        BUILDX_CACHE_MODE_MIN: "false"
        CLONING_MODE: FULL
        SCOPED_VARIABLE_ENABLED: "true"
        SCOPED_VARIABLE_HANDLE_PRIMITIVES: "true"
        DEVTRON_CHART_ARGO_CD_INSTALL_REQUEST_TIMEOUT: "1"
        IS_INTERNAL_USE: "true"
        IS_AIR_GAP_ENVIRONMENT: "false"
        DEVTRON_MANAGED_LICENSING_ENABLED: "false"
        GRPC_ENFORCE_ALPN_ENABLED: "false"
        KRR_SCAN_LISTING_PARALLELISM_LIMIT: "2"
        KRR_SYNC_SERVICE_ACCOUNT: devtron
        KRR_DOCKER_IMAGE: "quay.io/devtron/krr:d829c010-1113-35596"
        KRR_MATRIX_TIME_RANGE: 720h
        KRR_ACTIVE_DEADLINE_SECONDS: "30000"
        HIDE_API_TOKENS: "true"
    # Values for ciRunner
    ciRunner:
      image: "ci-runner:65e37985-1020-35597"
    # Values for kubelink
    kubelink:
      image: "kubelink:f1033317-314-36107"
      imagePullPolicy: IfNotPresent
    # Values for gitsensor
    gitsensor:
      image: "git-sensor:d829c010-950-35581"
      imagePullPolicy: IfNotPresent
    chartSync:
      image: chart-sync:d829c010-1021-35583
    postgres:
      image: "postgres:14.9"
      metrics:
        image: "postgres_exporter:v0.10.1"
  # values for security integration
  security:
    imageScanner:
      image: "image-scanner:d829c010-109-35580"
      configs:
        TRIVY_DB_REPOSITORY: mirror.gcr.io/aquasec/trivy-db
        TRIVY_JAVA_DB_REPOSITORY: mirror.gcr.io/aquasec/trivy-java-db
  devtronEnterprise:
    enabled: true
    casbin:
      image: "casbin:36c5edc6-75a2edd0-464-35582"
      imagePullPolicy: IfNotPresent
    scoop:
      enabled: false
      image: "scoop:d829c010-955-35585"
      imagePullPolicy: IfNotPresent
