global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true
  containerRegistry: "quay.io/devtron"
  # The below values can be specified both at global as well as component level
  # nodeSelector:
  #   key: value
  # tolerations:
  #   - key: "key1"
  #     operator: "Equal"
  #     value: "value1"
  #     effect: "NoSchedule"
  # imagePullSecrets:
  #     - name: your-image-pull-secret
  dbConfig:
    PG_ADDR: postgresql-postgresql.devtroncd
    PG_PORT: "5432"
    PG_USER: postgres
    PG_DATABASE: orchestrator
devtron:
  installer:
    repo: "devtron-labs/charts"
    release: "37.0.0"
    registry: ""
    arch: "multi-arch"
    image: inception
    tag: 7beef376-948-31378
    source: "github" # Available options are github and gitee
  components:
    # Values for dashboard
    dashboard:
      config:
        extraConfigs:
          HIDE_DISCORD: "true"
          HIDE_RELEASES: "false"
          HIDE_RESOURCE_WATCHER: "false"
          FEATURE_SCOPED_VARIABLE_ENVIRONMENT_LIST_ENABLE: "true"
          FEATURE_IMAGE_PROMOTION_ENABLE: "true"
          FEATURE_CLUSTER_MAP_ENABLE: "true"
          FEATURE_CONFIG_DRIFT_ENABLE: "true"
      image: "dashboard:eeb574a6-4a5dcfc1-931-34348"
    # Values for devtron
    devtron:
      image: "hyperion:d0517a76-759-34346"
      cicdImage: "devtron:d0517a76-930-34350"
      imagePullPolicy: IfNotPresent
      customOverrides:
        PG_ADDR: postgresql-postgresql.devtroncd
        USE_CUSTOM_HTTP_TRANSPORT: "false"
        ASYNC_BUILDX_CACHE_EXPORT: "false"
        BUILDX_CACHE_MODE_MIN: "false"
        CLONING_MODE: FULL
        SCOPED_VARIABLE_ENABLED: "true"
        SCOPED_VARIABLE_HANDLE_PRIMITIVES: "true"
        DEVTRON_CHART_ARGO_CD_INSTALL_REQUEST_TIMEOUT: "1"
        IS_INTERNAL_USE: "true"
        IS_AIR_GAP_ENVIRONMENT: "false"
        DEVTRON_MANAGED_LICENSING_ENABLED: "false"
    # Values for ciRunner
    ciRunner:
      image: "ci-runner:48c3bdb7-1020-34034"
    # Values for kubelink
    kubelink:
      image: "kubelink:cbfb2eb9-314-34351"
      imagePullPolicy: IfNotPresent
    # Values for gitsensor
    gitsensor:
      image: "git-sensor:48c3bdb7-950-34036"
      imagePullPolicy: IfNotPresent
    chartSync:
      image: chart-sync:48c3bdb7-1021-34037
    postgres:
      image: "postgres:14.9"
      metrics:
        image: "postgres_exporter:v0.10.1"
  # values for security integration
  security:
    imageScanner:
      image: "image-scanner:48c3bdb7-109-34038"
      configs:
        TRIVY_DB_REPOSITORY: mirror.gcr.io/aquasec/trivy-db
        TRIVY_JAVA_DB_REPOSITORY: mirror.gcr.io/aquasec/trivy-java-db
  devtronEnterprise:
    enabled: true
    casbin:
      image: "casbin:48c3bdb7-8243120a-464-34039"
      imagePullPolicy: IfNotPresent
    scoop:
      enabled: false
      image: "scoop:48c3bdb7-955-34040"
      imagePullPolicy: IfNotPresent
