global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true
  containerRegistry: "quay.io/devtron"
  # The below values can be specified both at global as well as component level
  # nodeSelector:
  #   key: value
  # tolerations:
  #   - key: "key1"
  #     operator: "Equal"
  #     value: "value1"
  #     effect: "NoSchedule"
  # imagePullSecrets:
  #     - name: your-image-pull-secret

  # Set the storage class to be used for PVCs (would use default sc if not specified)
  storageClass: ""
  # Add Proxy Configs to be propagated to all the Devtron Microservices.
  configs: {}
  nodeSelector: {}
  tolerations: []
  imagePullSecrets: []
devtron:
  installer:
    repo: "devtron-labs/charts"
    release: "33.0.0"
    registry: ""
    image: inception
    tag: 7beef376-948-31378
    source: "github" # Available options are github and gitee
    modules:
      - cicd # Available options are cicd
    openshift: false # Set this to true if you are installing on openshift
    production_overrides: "" # Set true if you want to use this Devtron stack in Production (This will require more resources)
  components:
    # Values for dashboard
    dashboard:
      config:
        extraConfigs:
          HIDE_DISCORD: "true"
          HIDE_RELEASES: "false"
          HIDE_RESOURCE_WATCHER: "false"
          FEATURE_SCOPED_VARIABLE_ENVIRONMENT_LIST_ENABLE: "true"
          FEATURE_IMAGE_PROMOTION_ENABLE: "true"
          FEATURE_CLUSTER_MAP_ENABLE: "true"
          FEATURE_CONFIG_DRIFT_ENABLE: "true"
      image: "dashboard:53af6e6e-2c45cf63-931-32723"
    # Values for devtron
    devtron:
      image: "hyperion:9291b79f-759-32326"
      cicdImage: "devtron:b2e663fa-930-32721"
      imagePullPolicy: IfNotPresent
      customOverrides:
        PG_ADDR: postgresql-postgresql.devtroncd
        USE_CUSTOM_HTTP_TRANSPORT: "false"
        ASYNC_BUILDX_CACHE_EXPORT: "false"
        BUILDX_CACHE_MODE_MIN: "false"
        CLONING_MODE: FULL
        SCOPED_VARIABLE_ENABLED: "true"
        SCOPED_VARIABLE_HANDLE_PRIMITIVES: "true"
        DEVTRON_CHART_ARGO_CD_INSTALL_REQUEST_TIMEOUT: "1"
        IS_INTERNAL_USE: "true"
        IS_AIR_GAP_ENVIRONMENT: "false"
        DEVTRON_MANAGED_LICENSING_ENABLED: "false"
    # Values for ciRunner
    ciRunner:
      image: "ci-runner:a4ad159b-515-32260"
    # Values for kubelink
    kubelink:
      image: "kubelink:a4ad159b-314-32327"
      imagePullPolicy: IfNotPresent
    # Values for gitsensor
    gitsensor:
      image: "git-sensor:a4ad159b-950-32328"
      imagePullPolicy: IfNotPresent
    chartSync:
      image: chart-sync:2380bb87-341-31847
    postgres:
      image: "postgres:14.9"
      metrics:
        image: "postgres_exporter:v0.10.1"
  # values for security integration
  security:
    enabled: true
    imageScanner:
      image: "image-scanner:a4ad159b-109-32332"
      configs:
        TRIVY_DB_REPOSITORY: mirror.gcr.io/aquasec/trivy-db
        TRIVY_JAVA_DB_REPOSITORY: mirror.gcr.io/aquasec/trivy-java-db
    trivy:
      enabled: true
  notifier:
    enabled: true
  monitoring:
    grafana:
      enabled: true
  devtronEnterprise:
    enabled: true
    casbin:
      image: "casbin:a4ad159b-9291b79f-464-32330"
      imagePullPolicy: IfNotPresent
    scoop:
      enabled: false
      image: "scoop:a4ad159b-955-32329"
      imagePullPolicy: IfNotPresent
