global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true
  containerRegistry: "quay.io/devtron"
  # The below values can be specified both at global as well as component level
  # nodeSelector:
  #   key: value
  # tolerations:
  #   - key: "key1"
  #     operator: "Equal"
  #     value: "value1"
  #     effect: "NoSchedule"
  # imagePullSecrets:
  #     - name: your-image-pull-secret

  # Set the storage class to be used for PVCs (would use default sc if not specified)
  storageClass: ""
  
  # Add Proxy Configs to be propagated to all the Devtron Microservices.
  configs: {}

  nodeSelector: {}
  tolerations: []
  imagePullSecrets: []
devtron:
  components:
    # Values for dashboard
    dashboard:
      config:
        extraConfigs:
          HIDE_DISCORD: "true"
          HIDE_RELEASES: "false"
          HIDE_RESOURCE_WATCHER: "false"
          FEATURE_SCOPED_VARIABLE_ENVIRONMENT_LIST_ENABLE: "true"
          FEATURE_IMAGE_PROMOTION_ENABLE: "true"
          FEATURE_CLUSTER_MAP_ENABLE: "true"
      image: "dashboard:f6810a22-bca87ef0-6-30145"
    # Values for devtron
    devtron:
      image: "hyperion:4e8fb93e-828-30473"
      cicdImage: "devtron:142690f6-4-31003"
      imagePullPolicy: IfNotPresent
      customOverrides:
        USE_CUSTOM_HTTP_TRANSPORT: "true"
        ASYNC_BUILDX_CACHE_EXPORT: "false"
        BUILDX_CACHE_MODE_MIN: "false"
        DEVTRON_INSTALLATION_TYPE: enterprise
        CLONING_MODE: FULL
        SCOPED_VARIABLE_ENABLED: "true"
        SCOPED_VARIABLE_HANDLE_PRIMITIVES: "true"
        DEVTRON_CHART_ARGO_CD_INSTALL_REQUEST_TIMEOUT: "1"
        IS_INTERNAL_USE: "true"
  	    IS_AIR_GAP_ENVIRONMENT: "false"
      podSecurityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1001
    # Values for ciRunner
    ciRunner:
      image: "ci-runner:2c6a094c-882-30828"
    # Values for kubelink
    kubelink:
      image: "kubelink:2c6a094c-310-30829"
      imagePullPolicy: IfNotPresent
      podSecurityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1001
    # Values for gitsensor
    gitsensor:
      image: "git-sensor:f4de0354-535-30999"
      imagePullPolicy: IfNotPresent
    chartSync:
      image: chart-sync:289d080a-341-30392
      podSecurityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1001
  # values for security integration
  security:
    imageScanner:
      image: "image-scanner:2c6a094c-112-30817"
      configs:
        TRIVY_DB_REPOSITORY: mirror.gcr.io/aquasec/trivy-db
        TRIVY_JAVA_DB_REPOSITORY: mirror.gcr.io/aquasec/trivy-java-db
  
  devtronEnterprise:
    enabled: true
    casbin:
      image: "casbin:f6ff5f74-064b67e5-462-30822"
      imagePullPolicy: IfNotPresent
      podSecurityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1001
    scoop:
      enabled: false
      image: "scoop:2c6a094c-629-30827"
      imagePullPolicy: IfNotPresent
