{{- if .Values.secretmap.enabled }}
apiVersion: v1
{{- if .Values.secretmap.data }}
data:
  {{- toYaml .Values.secretmap.data | nindent 2 }}
{{- end }}
kind: Secret
metadata:
  name: secret-map-deepak
type: Opaque
{{- end }}
