{{- if .Values.global.S3.enabled }}
{{- if or .Values.postgres_backup.enabled .Values.argocd_backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: devtron-s3-backup-secret
type: Opaque
data:
  {{- with .Values.global.S3 }}
  - name: S3_BUCKET_NAME
    value: {{ .S3_BUCKET_NAME }}
  - name: S3_ACCESS_KEY
    value: {{ .S3_ACCESS_KEY }}
  - name: S3_SECRET_KEY
    value: {{ .S3_SECRET_KEY }}
  - name: S3_REGION
    value: {{ .S3_REGION | default "us-east-1" }} 
  {{- end }}
{{- end }}
{{- end }}