apiVersion: v1
kind: Secret
metadata:
  name: devtron-azure-backup-secret
type: Opaque
data:
  {{- with .Values.global.AZURE }}
  - name: AZURE_BLOB_ACCOUNT_NAME
    value: "{{ .AZURE_BLOB_ACCOUNT_NAME }}"
  - name: AZURE_ACCOUNT_KEY
    value: {{ .AZURE_ACCOUNT_KEY }}
  - name: AZURE_BLOB_CONTAINER_FOR_POSTGRES
    value: {{ .AZURE_BLOB_CONTAINER_FOR_POSTGRES }}
  - name: AZURE_BLOB_CONTAINER_FOR_ARGOCD
    value: {{ .AZURE_BLOB_CONTAINER_FOR_ARGOCD }}
  {{- end }}