apiVersion: v1
data:
  {{- with .Values.workflow.config }}
  config: |
    {{- toYaml . | nindent 4 }}
  {{- end }}     
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: devtroncd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch-config
  namespace: devtroncd
data:
  {{- with .Values.kubewatch.config }}
  .kubewatch.yaml: |
     {{- toYaml . | nindent 4 }}
  {{- end }}
       