
{{- if $.Values.workflow.use_access_secret_key }}
{{- range .Values.execute_in_application_env.namespaces }}
apiVersion: v1
metadata:
  name: workflow-minio-cred
  namespace: {{ . }}
data:
  accessKey: {{ $.Values.workflow.accesskey | b64enc }} 
  secretKey: {{ $.Values.workflow.secretkey | b64enc }} 
kind: Secret
---
{{- end }}
{{- end }}