---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: devtroncd
---
{{- range .Values.execute_in_application_env.namespaces }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd-runner
  namespace: {{ . }}
---
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubewatch
  namespace: devtroncd