{{- if $.Release.IsInstall }}
{{- if .Capabilities.APIVersions.Has "batch/v1/Job" }}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: Job
metadata:
  name: app-sync-job-{{ randAlphaNum 5 | lower }}
spec:
  template:
    spec:
      serviceAccountName: devtron
      initContainers:
      - name: migration-wait
        image: "quay.io/devtron/kubectl:latest"
        command: ['sh', '-c', 'while [ ! $(kubectl -n devtroncd get $(kubectl -n devtroncd get job -l job=postgresql-migrate-devtron -o name) -o jsonpath="{.status.succeeded}")  ]; do sleep 10; done']
        {{- if .Values.components.migrator }}
        {{- if .Values.components.migrator.appSync }}
        {{- if .Values.components.migrator.appSync.initContainer }}
        {{- if .Values.components.migrator.appSync.initContainer.resources }}
        resources:
        {{- toYaml .Values.components.migrator.appSync.initContainer.resources | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
      containers:
      - name: chart-sync
        image: quay.io/devtron/chart-sync:07ac8fd7-150-11120
        env:
        - name: PG_ADDR
          value: postgresql-postgresql.devtroncd
        - name: PG_DATABASE
          value: orchestrator
        - name: PG_USER
          value: postgres
        envFrom:
        - secretRef:
            name: devtron-secret
        {{- if .Values.components.migrator }}
        {{- if .Values.components.migrator.appSync }}
        {{- if .Values.components.migrator.appSync.resources }}
        resources:
        {{- toYaml .Values.components.migrator.appSync.resources | nindent 14 }}
        {{- end }}
        {{- end }}
        {{- end }}
      restartPolicy: OnFailure
      {{- if .Values.components.migrator }}
      {{- if .Values.components.migrator.appSync }}
      {{- if or  $.Values.components.migrator.appSync.affinity  (and $.Values.global $.Values.global.affinity) }}
      {{- with  $.Values.components.migrator.appSync.affinity | default $.Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if or $.Values.components.migrator.appSync.tolerations  (and $.Values.global $.Values.global.tolerations ) }}
      {{- with $.Values.components.migrator.appSync.tolerations | default $.Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if or $.Values.components.migrator.appSync.nodeSelector   (and $.Values.global $.Values.global.nodeSelector ) }}
      {{- with $.Values.components.migrator.appSync.nodeSelector | default $.Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
  backoffLimit: 4
---
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: app-sync-cronjob
  annotations:
    "helm.sh/resource-policy": keep
spec:
  schedule: "0 19 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: chart-sync
            image: quay.io/devtron/chart-sync:07ac8fd7-150-11120
            env:
            - name: PG_ADDR
              value: postgresql-postgresql.devtroncd
            - name: PG_DATABASE
              value: orchestrator
            - name: PG_USER
              value: postgres
            envFrom:
            - secretRef:
                name: devtron-secret
            {{- if .Values.components.migrator }}
            {{- if .Values.components.migrator.appSync }}
            {{- if .Values.components.migrator.appSync.resources }}
            resources:
            {{- toYaml .Values.components.migrator.appSync.resources | nindent 14 }}
            {{- end }}
            {{- end }}
            {{- end }}
          restartPolicy: Never
      backoffLimit: 4
