{{- with .Values.components.kubelink }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubelink
  labels:
    app: kubelink
    chart: kubelink-4.11.1
  annotations:
    "helm.sh/resource-policy": keep
spec:
  selector:
    matchLabels:
      app: kubelink
  replicas: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: kubelink
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      {{- if or $.Values.components.kubelink.affinity  (and $.Values.global $.Values.global.affinity) }}
      {{- with $.Values.components.kubelink.affinity | default $.Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if or $.Values.components.kubelink.tolerations  (and $.Values.global $.Values.global.tolerations ) }}
      {{- with $.Values.components.kubelink.tolerations | default $.Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if or $.Values.components.kubelink.nodeSelector  (and $.Values.global $.Values.global.nodeSelector ) }}
      {{- with $.Values.components.kubelink.nodeSelector | default $.Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccount: devtron
      containers:
        - name: kubelink
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports:
            - name: app
              containerPort: 50051
              protocol: TCP
          env:
            - name: DEVTRON_APP_NAME
              value: kubelink
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- if .resources }}        
          resources:
          {{- toYaml .resources | nindent 12 }}
          {{- end }}                  
  revisionHistoryLimit: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubelink
  name: kubelink-service
  namespace: devtroncd
  annotations:
    "helm.sh/resource-policy": keep
spec:
  ports:
    - name: app
      port: 50051
      protocol: TCP
      targetPort: app
  selector:
    app: kubelink
  sessionAffinity: None
  type: ClusterIP
{{- end }}