{{- if or (eq .Values.installer.mode "hyperion") (eq .Values.installer.mode "Hyperion") }}
{{- with .Values.hyperion.migrator }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-migrate-devtron
  annotations:
    "helm.sh/resource-policy": keep
spec:
  ttlSecondsAfterFinished: 1000
  template:
    spec:
      containers:
      - name: postgresql-migrate-devtron
        image: {{ .image }}
        env:
        - name: GIT_BRANCH
          value: {{ .envVars.devtron.GIT_BRANCH }}
        - name: SCRIPT_LOCATION
          value: {{ .envVars.devtron.SCRIPT_LOCATION }}
        - name: GIT_REPO_URL
          value: {{ .envVars.devtron.GIT_REPO_URL }}
        - name: DB_TYPE
          value: postgres
        - name: DB_USER_NAME
          value: postgres
        - name: DB_HOST
          value: postgresql-postgresql.devtroncd
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: {{ .envVars.devtron.DB_NAME }}
        - name: MIGRATE_TO_VERSION
          value: "0"
        - name: GIT_HASH
          value: {{ .envVars.devtron.GIT_HASH }}
        envFrom:
          - secretRef:
              name: postgresql-migrator
      restartPolicy: OnFailure
      {{- if and $.Values.hyperion.global.nodeSelector .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- else if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- else if $.Values.hyperion.global.nodeSelector }}
      nodeSelector:
        {{- toYaml $.Values.hyperion.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if and $.Values.hyperion.global.tolerations .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- else if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- else if $.Values.hyperion.global.tolerations }}
      tolerations:
        {{- toYaml $.Values.hyperion.global.tolerations | nindent 8 }}
      {{- end }}
  backoffLimit: 20
  activeDeadlineSeconds: 1500
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-migrate-casbin
  annotations:
    "helm.sh/resource-policy": keep
spec:
  template:
    spec:
      serviceAccountName: devtron
      containers:
      - name: devtron-rollout
        image: quay.io/bitnami/kubectl:latest
        command: ['sh', '-c', 'kubectl rollout restart deployment/devtron -n devtroncd']
      initContainers:
      - name: postgresql-migrate-casbin
        image: {{ .image }}
        env:
        - name: SCRIPT_LOCATION
          value: {{ .envVars.casbin.SCRIPT_LOCATION }}
        - name: GIT_REPO_URL
          value: {{ .envVars.casbin.GIT_REPO_URL }}
        - name: DB_TYPE
          value: postgres
        - name: DB_USER_NAME
          value: postgres
        - name: DB_HOST
          value: postgresql-postgresql.devtroncd
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: {{ .envVars.casbin.DB_NAME }}
        - name: MIGRATE_TO_VERSION
          value: "0"
        - name: GIT_HASH
          value: {{ .envVars.casbin.GIT_HASH }}
        - name: GIT_BRANCH
          value: {{ .envVars.casbin.GIT_BRANCH }}
        envFrom:
          - secretRef:
              name: postgresql-migrator
        resources:
          requests:
            cpu: 0.5
            memory: 500Mi
      restartPolicy: OnFailure
      {{- if and $.Values.hyperion.global.nodeSelector .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- else if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- else if $.Values.hyperion.global.nodeSelector }}
      nodeSelector:
        {{- toYaml $.Values.hyperion.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if and $.Values.hyperion.global.tolerations .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- else if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- else if $.Values.hyperion.global.tolerations }}
      tolerations:
        {{- toYaml $.Values.hyperion.global.tolerations | nindent 8 }}
      {{- end }}
  backoffLimit: 20
  activeDeadlineSeconds: 1500
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-sync-cronjob
  annotations:
    "helm.sh/resource-policy": keep
spec:
  schedule: "0 19 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: chart-sync
            image: quay.io/devtron/chart-sync:1227622d-132-3775
            env:
            - name: PG_ADDR
              value: postgresql-postgresql.devtroncd
            - name: PG_DATABASE
              value: orchestrator
            - name: PG_USER
              value: postgres
            envFrom:
            - secretRef:
                name: devtron-secret
          restartPolicy: Never
          {{- if and $.Values.hyperion.global.nodeSelector .nodeSelector }}
          nodeSelector:
            {{- toYaml .nodeSelector | nindent 12 }}
          {{- else if .nodeSelector }}
          nodeSelector:
            {{- toYaml .nodeSelector | nindent 12 }}
          {{- else if $.Values.hyperion.global.nodeSelector }}
          nodeSelector:
            {{- toYaml $.Values.hyperion.global.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if and $.Values.hyperion.global.tolerations .tolerations }}
          tolerations:
            {{- toYaml .tolerations | nindent 12 }}
          {{- else if .tolerations }}
          tolerations:
            {{- toYaml .tolerations | nindent 12 }}
          {{- else if $.Values.hyperion.global.tolerations }}
          tolerations:
            {{- toYaml $.Values.hyperion.global.tolerations | nindent 12 }}
          {{- end }}
      backoffLimit: 4
{{- end }}
{{- end }}